#!/usr/bin/env python

# Copyright (c) 2013 Galah Group LLC
# Copyright (c) 2013 Other contributers as noted in the CONTRIBUTERS file
#
# This file is part of galah-apiclient.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if __name__ != "__main__":
    raise ImportError("This is a script and should not be imported.")

import sys
import pprint

# Initialize the logging library.
import apiclient.logcontrol
import logging
apiclient.logcontrol.init_logging()
logger = logging.getLogger("apiclient")

# Load up the configuration
import apiclient.config as config
config.CONFIG = config.load_config()
if "verbosity" in config.CONFIG:
    apiclient.logcontrol.set_level(config.CONFIG["verbosity"])
logger.debug(
    "Final configuration dictionary...\n%s",
    pprint.pformat(config.CONFIG, width = 72)
)

# Grab the user's old session information.
import apiclient.communicate
session = apiclient.communicate.APIClientSession()
session.load()

# Login if necessary
import apiclient.ui
if session.user is None:
    session.login(*apiclient.ui.determine_credentials())

# Perform the command the user wants to execute
command_args, command_kwargs = apiclient.ui.parse_raw_args(config.ARGS)
